// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1nOIwf_2IrwWmYHx0FWtsrAIbmjEA3Rk',
    appId: '1:469458129138:web:11940ec5f93494808e806b',
    messagingSenderId: '469458129138',
    projectId: 'med-scheduler-front',
    authDomain: 'med-scheduler-front.firebaseapp.com',
    storageBucket: 'med-scheduler-front.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RRAjeyHmJS-E2mT1IYYy7kIrMiOzdQY',
    appId: '1:469458129138:android:52e51364eb9c51258e806b',
    messagingSenderId: '469458129138',
    projectId: 'med-scheduler-front',
    storageBucket: 'med-scheduler-front.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMmdf-rv7zCJ5usQZnsuW_qk5k3LgJfw',
    appId: '1:469458129138:ios:a1be872afabc67368e806b',
    messagingSenderId: '469458129138',
    projectId: 'med-scheduler-front',
    storageBucket: 'med-scheduler-front.appspot.com',
    iosBundleId: 'com.example.medSchedulerFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMmdf-rv7zCJ5usQZnsuW_qk5k3LgJfw',
    appId: '1:469458129138:ios:d6b3843c9192b4578e806b',
    messagingSenderId: '469458129138',
    projectId: 'med-scheduler-front',
    storageBucket: 'med-scheduler-front.appspot.com',
    iosBundleId: 'com.example.medSchedulerFront.RunnerTests',
  );
}
